version: '3.8'

services:
    mongo:
        image: mongo
        container_name: mongo
        ports:
            - '27017:27017'
        volumes:
            - ./mongo-data:/data/db
            - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: root_password
            MONGO_INITDB_DATABASE: webboard
        networks:
            - mongo

networks:
    mongo:
        driver: bridge
